using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Problem44
{
    class Program
    {
        private const int iterations = 10000;

        static void Main(string[] args)
        {
            /*
                Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
                1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... 
                It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
                Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
            */
            var generator = new PentagonalGenerator();

            //Search in diffences for a match
            //Stop looking when difference is smaller then the next differenc in the list... could never work
            int p1 = 1;
            int p2 = 3;
            bool bFound = false;
            long foundDifference = -1;
            while(!bFound && p1 < iterations)
            {
                long difference = generator.GetDifference(p1, p2);
                if (generator.IsPentagonalNumber(difference))
                {
                    //Check sum
                    if(generator.IsPentagonalNumber(generator.GetPentagonalNumber(p1)+generator.GetPentagonalNumber(p2)))
                    {
                        bFound = true;
                        foundDifference = (Math.Min(foundDifference, difference));
                        Console.WriteLine($"Found two numbers {p1} & {p2}");
                        Console.WriteLine($"Difference is {difference}");
                    }

                }
                //search next pairing
                if ( p1 < 2)
                {
                    p2++;
                    p1 = p2 - 1;
                    Console.WriteLine($"Searching for number {p2}");
                }
                else
                {
                    p1--;
                }

            }
            if(bFound)
            {
                Console.WriteLine($"Difference is {foundDifference}");
            }else
            {
                Console.WriteLine("Found Nothing");
            }
            Console.ReadLine();

            
        }
    }
}
